#include "audio.h"
#include <nds.h>

// WAV headers generated by bin2s — contain extern array decls + constexpr size
#include "shoot_wav.h"
#include "explode_wav.h"
#include "pickup_gold_wav.h"
#include "merge_wav.h"
#include "hit_wav.h"
#include "select_wav.h"
#include "dash_wav.h"
#include "buy_wav.h"
#include "sell_wav.h"
#include "reroll_wav.h"
#include "wave_clear_wav.h"
#include "wave_start_wav.h"
#include "player_hit_wav.h"
#include "perk_sfx_wav.h"
#include "boss_appear_wav.h"
#include "timestop_wav.h"
#include "heal_wav.h"
#include "sfx_synergy_wav.h"

// SFX lookup: maps GSFX_ enum to WAV data pointer and size
struct WavEntry { const u8* data; size_t size; };
static const WavEntry sfxTable[GSFX_COUNT] = {
    { shoot_wav,       shoot_wav_size },        // GSFX_SHOOT
    { explode_wav,     explode_wav_size },       // GSFX_EXPLODE
    { pickup_gold_wav, pickup_gold_wav_size },   // GSFX_GOLD
    { merge_wav,       merge_wav_size },         // GSFX_MERGE
    { hit_wav,         hit_wav_size },           // GSFX_HIT
    { select_wav,      select_wav_size },        // GSFX_SELECT
    { dash_wav,        dash_wav_size },          // GSFX_DASH
    { buy_wav,         buy_wav_size },           // GSFX_BUY
    { sell_wav,        sell_wav_size },           // GSFX_SELL
    { reroll_wav,      reroll_wav_size },        // GSFX_REROLL
    { wave_clear_wav,  wave_clear_wav_size },    // GSFX_WAVE_CLEAR
    { wave_start_wav,  wave_start_wav_size },    // GSFX_WAVE_START
    { player_hit_wav,  player_hit_wav_size },    // GSFX_PLAYER_HIT
    { perk_sfx_wav,    perk_sfx_wav_size },       // GSFX_PERK
    { boss_appear_wav, boss_appear_wav_size },   // GSFX_BOSS
    { timestop_wav,    timestop_wav_size },      // GSFX_TIMESTOP
    { heal_wav,        heal_wav_size },          // GSFX_HEAL
    { sfx_synergy_wav, sfx_synergy_wav_size },       // GSFX_SYNERGY
};

void audioInit() {
    soundEnable();
}

// Find the 'data' chunk in a WAV file, return pointer to PCM and set len
static const u8* wavFindData(const u8* wav, size_t fileSize, size_t& outLen) {
    // Skip RIFF header (12 bytes), then scan chunks
    size_t pos = 12;
    while (pos + 8 <= fileSize) {
        u32 chunkSize = wav[pos+4] | (wav[pos+5]<<8) | (wav[pos+6]<<16) | (wav[pos+7]<<24);
        if (wav[pos]=='d' && wav[pos+1]=='a' && wav[pos+2]=='t' && wav[pos+3]=='a') {
            outLen = chunkSize;
            if (pos + 8 + outLen > fileSize) outLen = fileSize - pos - 8;
            return wav + pos + 8;
        }
        pos += 8 + chunkSize;
        if (chunkSize & 1) pos++; // WAV chunks are 2-byte aligned
    }
    outLen = 0;
    return nullptr;
}

// Per-SFX volume and pitch tuning: softer, less aggressive
// Lower sample rate = deeper/softer tone. Lower volume = quieter.
struct SfxTuning { u8 volume; u16 rate; };
static const SfxTuning sfxTuning[GSFX_COUNT] = {
    {  5, 11000},  // SHOOT — barely audible whisper
    {  4,  8000},  // EXPLODE — near-silent ultra-muffled thump
    { 20, 14000},  // GOLD — gentle clink
    { 30, 14000},  // MERGE — soft chime
    { 15, 11000},  // HIT — soft muffled thud
    { 18, 14000},  // SELECT — tiny click
    { 20, 11000},  // DASH — soft whoosh
    { 20, 14000},  // BUY — soft ping
    { 18, 14000},  // SELL — soft
    { 15, 14000},  // REROLL — soft shuffle
    { 25, 14000},  // WAVE_CLEAR — moderate, not loud
    { 22, 14000},  // WAVE_START — soft alert
    { 20, 11000},  // PLAYER_HIT — muffled impact
    { 25, 14000},  // PERK — soft chime
    { 30, 11000},  // BOSS — moderate deep
    { 20, 11000},  // TIMESTOP — soft freeze
    { 18, 14000},  // HEAL — gentle warm tone
    { 22, 14000},  // SYNERGY — soft magical
};

void audioPlaySfx(SfxId id) {
    if (id >= GSFX_COUNT) return;
    const WavEntry& w = sfxTable[id];
    size_t pcmLen = 0;
    const u8* pcm = wavFindData(w.data, w.size, pcmLen);
    if (!pcm || pcmLen < 16) return;
    const SfxTuning& t = sfxTuning[id];
    soundPlaySample(pcm, SoundFormat_8Bit, pcmLen, t.rate, t.volume, 64, false, 0);
}

void audioPlayMusic([[maybe_unused]] int id) {
    // Music disabled — maxmod fights with soundPlaySample over hardware channels.
    // TODO: re-enable once calico ARM7 channel separation is solved.
}

void audioStopMusic() {
    // No-op while music is disabled
}
