#include "audio.h"
#include <nds.h>

// WAV headers generated by bin2s — contain extern array decls + constexpr size
#include "shoot_wav.h"
#include "explode_wav.h"
#include "pickup_gold_wav.h"
#include "merge_wav.h"
#include "hit_wav.h"
#include "select_wav.h"
#include "dash_wav.h"
#include "buy_wav.h"
#include "sell_wav.h"
#include "reroll_wav.h"
#include "wave_clear_wav.h"
#include "wave_start_wav.h"
#include "player_hit_wav.h"
#include "perk_sfx_wav.h"
#include "boss_appear_wav.h"
#include "timestop_wav.h"
#include "heal_wav.h"
#include "sfx_synergy_wav.h"
#include "enemy_shoot_wav.h"

// Music WAV data (6-second loops, embedded via bin2s)
#include "mus_menu_wav.h"
#include "mus_battle_wav.h"
#include "mus_shop_wav.h"
#include "mus_boss_wav.h"
#include "mine_place_wav.h"
#include "boss_phase_wav.h"
#include "victory_wav.h"

// SFX lookup: maps GSFX_ enum to WAV data pointer and size
struct WavEntry { const u8* data; size_t size; };
static const WavEntry sfxTable[GSFX_COUNT] = {
    { shoot_wav,       shoot_wav_size },        // GSFX_SHOOT
    { explode_wav,     explode_wav_size },       // GSFX_EXPLODE
    { pickup_gold_wav, pickup_gold_wav_size },   // GSFX_GOLD
    { merge_wav,       merge_wav_size },         // GSFX_MERGE
    { hit_wav,         hit_wav_size },           // GSFX_HIT
    { select_wav,      select_wav_size },        // GSFX_SELECT
    { dash_wav,        dash_wav_size },          // GSFX_DASH
    { buy_wav,         buy_wav_size },           // GSFX_BUY
    { sell_wav,        sell_wav_size },           // GSFX_SELL
    { reroll_wav,      reroll_wav_size },        // GSFX_REROLL
    { wave_clear_wav,  wave_clear_wav_size },    // GSFX_WAVE_CLEAR
    { wave_start_wav,  wave_start_wav_size },    // GSFX_WAVE_START
    { player_hit_wav,  player_hit_wav_size },    // GSFX_PLAYER_HIT
    { perk_sfx_wav,    perk_sfx_wav_size },       // GSFX_PERK
    { boss_appear_wav, boss_appear_wav_size },   // GSFX_BOSS
    { timestop_wav,    timestop_wav_size },      // GSFX_TIMESTOP
    { heal_wav,        heal_wav_size },          // GSFX_HEAL
    { sfx_synergy_wav, sfx_synergy_wav_size },       // GSFX_SYNERGY
    { enemy_shoot_wav, enemy_shoot_wav_size },     // GSFX_ENEMY_SHOOT
    { mine_place_wav,  mine_place_wav_size },      // GSFX_MINE_PLACE
    { boss_phase_wav,  boss_phase_wav_size },      // GSFX_BOSS_PHASE
    { victory_wav,     victory_wav_size },          // GSFX_VICTORY
};

void audioInit() {
    soundEnable();
}

// Find the 'data' chunk in a WAV file, return pointer to PCM and set len
static const u8* wavFindData(const u8* wav, size_t fileSize, size_t& outLen) {
    // Skip RIFF header (12 bytes), then scan chunks
    size_t pos = 12;
    while (pos + 8 <= fileSize) {
        u32 chunkSize = wav[pos+4] | (wav[pos+5]<<8) | (wav[pos+6]<<16) | (wav[pos+7]<<24);
        if (wav[pos]=='d' && wav[pos+1]=='a' && wav[pos+2]=='t' && wav[pos+3]=='a') {
            outLen = chunkSize;
            if (pos + 8 + outLen > fileSize) outLen = fileSize - pos - 8;
            return wav + pos + 8;
        }
        pos += 8 + chunkSize;
        if (chunkSize & 1) pos++; // WAV chunks are 2-byte aligned
    }
    outLen = 0;
    return nullptr;
}

// Per-SFX volume tuning — original sample rates preserved, just quiet
struct SfxTuning { u8 volume; u16 rate; };
static const SfxTuning sfxTuning[GSFX_COUNT] = {
    {  5, 22050},  // SHOOT — barely there
    {  3, 22050},  // EXPLODE
    {  5, 22050},  // GOLD
    { 22, 22050},  // MERGE
    { 18, 22050},  // HIT
    { 13, 22050},  // SELECT
    {  7, 22050},  // DASH
    { 13, 22050},  // BUY
    { 13, 22050},  // SELL
    { 10, 22050},  // REROLL
    {  3, 22050},  // WAVE_CLEAR
    {  3, 22050},  // WAVE_START
    {  4, 22050},  // PLAYER_HIT
    { 17, 22050},  // PERK
    { 18, 22050},  // BOSS
    { 13, 22050},  // TIMESTOP
    { 13, 22050},  // HEAL
    { 15, 22050},  // SYNERGY
    {  6, 22050},  // ENEMY_SHOOT
    { 18, 22050},  // MINE_PLACE
    { 26, 22050},  // BOSS_PHASE
    { 30, 22050},  // VICTORY
};

void audioPlaySfx(SfxId id) {
    if (id >= GSFX_COUNT) return;
    const WavEntry& w = sfxTable[id];
    size_t pcmLen = 0;
    const u8* pcm = wavFindData(w.data, w.size, pcmLen);
    if (!pcm || pcmLen < 16) return;
    const SfxTuning& t = sfxTuning[id];
    soundPlaySample(pcm, SoundFormat_8Bit, pcmLen, t.rate, t.volume, 64, false, 0);
}

// Music: play looping WAV sample on channel 0 (reserved for music)
static const WavEntry musicTable[] = {
    { mus_menu_wav,   mus_menu_wav_size },    // 0 = menu
    { mus_battle_wav, mus_battle_wav_size },   // 1 = battle
    { mus_shop_wav,   mus_shop_wav_size },     // 2 = shop (unused for now)
    { mus_boss_wav,   mus_boss_wav_size },     // 3 = boss (unused for now)
    { mus_shop_wav,   mus_shop_wav_size },     // 4 = shop (alias)
};
static int currentMusic = -1;
static int musicSoundId = -1;

void audioPlayMusic(int id) {
    if (id == currentMusic) return;
    if (id < 0 || id > 4) return;

    // Stop current music if playing
    if (musicSoundId >= 0) {
        soundKill(musicSoundId);
        musicSoundId = -1;
    }

    const WavEntry& m = musicTable[id];
    size_t pcmLen = 0;
    const u8* pcm = wavFindData(m.data, m.size, pcmLen);
    if (!pcm || pcmLen < 64) { currentMusic = -1; return; }

    // 16-bit 11025Hz looping music — per-track volume
    // Menu and shop are sparser/quieter tracks, need more volume on real hardware
    static const u8 musicVol[] = { 110, 70, 70, 80, 70 }; // menu(extra loud), battle, shop(unused), boss, shop
    u8 vol = (id >= 0 && id <= 4) ? musicVol[id] : 60;
    musicSoundId = soundPlaySample(pcm, SoundFormat_16Bit, pcmLen, 11025, vol, 64, true, 0);
    currentMusic = id;
}

void audioStopMusic() {
    if (musicSoundId >= 0) {
        soundKill(musicSoundId);
        musicSoundId = -1;
    }
    currentMusic = -1;
}
